version: '3'

services:
  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    depends_on:
      - app
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    ports:
      - "8080:80"

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - ./node/node_modules
    command: sh -c "npm install && node index.js"
    tty: true
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./start.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
